---
# Copyright 2017 Cisco Systems
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create database
  mysql_db: collation={{ mysql_db_collation }}
            encoding={{ mysql_db_encoding }}
            name=ironic
  no_log: True
  run_once: True

- name: Create database user
  mysql_user: append_privs={{ item.append_privs|default(omit)  }}
              check_implicit_admin={{ item.check_implicit|default(omit)  }}
              config_file={{ item.config_file|default(omit)  }}
              encrypted={{ item.encrypted|default(omit)  }}
              host={{ item.host|default(omit)  }}
              host_all={{ item.host_all|default(omit)  }}
              login_host={{ item.login_host|default(omit)  }}
              login_password={{ item.login_password|default(omit)  }}
              login_port={{ item.login_port|default(omit)  }}
              login_unix_socket={{ percona_socket  }}
              login_user={{ item.login_user|default(omit)  }}
              name={{ item.name|default(omit)  }}
              password={{ item.password|default(omit)  }}
              priv={{ item.priv|default(omit)  }}
              ssl_ca={{ item.ssl_ca|default(omit)  }}
              ssl_cert={{ item.ssl_cert|default(omit)  }}
              ssl_key={{ item.ssl_key|default(omit)  }}
              state={{ item.state|default(omit)  }}
              update_password={{ item.update_password|default(omit)  }}
  with_items: "{{ ironic_users_to_create | format_mysql_users  }}"
  no_log: True
  run_once: True

- name: Update database schema
  command: "{{ ironic_bin }}/ironic-dbsync upgrade"
  become: yes
  become_user: "{{ ironic_system_user_name }}"
  changed_when: false
  notify:
    - Restart ironic services
